name: Client CI

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  checks:
    uses: revisium/revisium-actions/.github/workflows/node-build.yml@763f2746000f15842e642130dba3acf09c5d00ac # v0.3.2
    with:
      node_version: 22.11.0
      install_command: npm ci
      run_commands: |
        npm run ts:check
        npm run fsd:check
        npm run lint:ci

  sonar:
    needs: checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
